name: mltype
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: 'python -m pip install --upgrade pip

          pip install .[dev,mlflow]

          '
      - id: measurement-4
        name: Record Measurement After Install Python dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install Python dependencies
          task: get-measurement
      - name: Lint with flake8
        run: 'flake8 mltype tests setup.py  # see tox.ini for config

          '
      - id: measurement-6
        name: Record Measurement After Lint with flake8
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Lint with flake8
          task: get-measurement
      - name: Check docstrings with pydocstyle
        run: 'pydocstyle mltype

          '
      - id: measurement-8
        name: Record Measurement After Check docstrings with pydocstyle
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check docstrings with pydocstyle
          task: get-measurement
      - continue-on-error: true
        name: Test with pytest
        run: 'pytest --color=yes  # see tox.ini for config

          '
      - id: measurement-10
        name: Record Measurement After Test with pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Test with pytest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740403494.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740403494.json
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.8
          - 3.9
          - '3.10'
